name: pandapower_sim
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pyside6>=6.7.3
  - pandapower>=3.1.2
  - numpy>=2.2.5
  - pandas>=2.3.1
  - matplotlib>=3.5
  - pyinstaller>=6.12
  - pip
  - pip:
    - pytest>=7.0.0
    - black>=22.0.0