name: pandapower_sim
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - conda-forge
dependencies:
  - python=3.12.11
  - pyside6=6.7.3
  - pandapower=3.1.2
  - numpy=2.2.5
  - pandas=2.3.1
  - matplotlib=3.10.0
  - pyinstaller=6.12.0
  - scipy=1.13.1
  - networkx=3.4.2
  - numba=0.61.2
  - lxml=5.3.0
  - geojson=3.2.0
  - deepdiff=7.0.1
  - tqdm=4.67.1
  - pip=25.1
  - setuptools=72.1.0
  - wheel=0.45.1
  - pip:
    - pytest>=7.0.0
    - black>=22.0.0