name: pandapower_sim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyside6>=6.0
  - pandapower=2.13
  - numpy=1.20
  - pandas=1.3
  - matplotlib=3.5
  - pyinstaller
  - pip
  - pip:
    - pytest>=7.0.0
    - black>=22.0.0